# Generated by Django 5.1.6 on 2025-05-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EachUserQueryHistory",
            fields=[
                (
                    "cookie_id",
                    models.CharField(
                        max_length=500, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("request", models.BooleanField(default=False)),
                ("request_query", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField()),
                ("lastModificationDate", models.CharField(max_length=500)),
                ("pageSize", models.IntegerField()),
                ("keywords", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="UserQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(default="", max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="main.eachuserqueryhistory",
                    ),
                ),
            ],
        ),
    ]
